name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout: Necessário para o commit automático funcionar
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      # 2. Snake Animation: Gera o SVG na raiz do repo
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: isocabp
          # AQUI: Mudamos o path para a raiz do repositório (apenas o nome do arquivo)
          svg_out_path: github-contribution-grid-snake.svg
          
      # 3. Commit: Commita o arquivo SVG na branch 'main'
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
